package com.parcelflow.common.enums;

public enum CustodyActionType {
    RECEIVED_FROM_CUSTOMER, HANDOVER_TO_HUB, HANDOVER_TO_DRIVER, RECEIVED_BY_DRIVER, RECEIVED_AT_DESTINATION_HUB, HANDOVER_TO_SHIPPER, RECEIVED_BY_SHIPPER, DELIVERED_TO_RECEIVER, DELIVERY_FAILED, RETURNED_TO_HUB, EXCEPTION_REPORTED
}
