package com.parcelflow.common.enums;

public enum OrderStatus {
    CREATED, RECEIVED_AT_ORIGIN_HUB, WAITING_FOR_ROUTE, IN_TRANSIT, ARRIVED_AT_FINAL_HUB, OUT_FOR_DELIVERY, DELIVERED, DELIVERY_FAILED, RETURNING, RETURNED, CANCELLED
}
