package com.parcelflow.common.enums;

public enum ParcelStatus {
    CREATED, RECEIVED_AT_ORIGIN_HUB, WAITING_FOR_ROUTE, WAITING_FOR_OUTBOUND, IN_TRANSIT, ARRIVED_AT_HUB, READY_FOR_DELIVERY, ASSIGNED_TO_SHIPPER, OUT_FOR_DELIVERY, DELIVERED, DELIVERY_FAILED, RETURNING, RETURNED, LOST, DAMAGED, CANCELLED
}
