export const USER_ROLES = {
  ADMIN: "ADMIN",
  HUB_MANAGER: "HUB_MANAGER",
  HUB_STAFF: "HUB_STAFF",
  DISPATCHER: "DISPATCHER",
  SHIPPER: "SHIPPER",
} as const;

export type UserRole = keyof typeof USER_ROLES;

export const PERMISSIONS = {
  // User permissions
  MANAGE_USERS: "MANAGE_USERS",

  // Hub permissions
  MANAGE_HUBS: "MANAGE_HUBS",

  // Order permissions
  CREATE_ORDERS: "CREATE_ORDERS",
  MANAGE_ORDERS: "MANAGE_ORDERS",

  // Parcel permissions
  CREATE_PARCELS: "CREATE_PARCELS",
  MANAGE_PARCELS: "MANAGE_PARCELS",
  UPDATE_PARCEL_STATUS: "UPDATE_PARCEL_STATUS",
  SCAN_INBOUND: "SCAN_INBOUND",
  SCAN_OUTBOUND: "SCAN_OUTBOUND",

  // Route & Delivery permissions
  CREATE_ROUTE_PLANS: "CREATE_ROUTE_PLANS",
  MANAGE_ROUTES: "MANAGE_ROUTES",
  ASSIGN_DELIVERY: "ASSIGN_DELIVERY",
  MANAGE_DELIVERY_ZONES: "MANAGE_DELIVERY_ZONES",

  // Dashboard permissions
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_OPERATIONAL_DASHBOARD: "VIEW_OPERATIONAL_DASHBOARD",
  VIEW_ASSIGNED_DELIVERIES: "VIEW_ASSIGNED_DELIVERIES",
  UPDATE_DELIVERY_STATUS: "UPDATE_DELIVERY_STATUS",
} as const;

export type Permission = keyof typeof PERMISSIONS;

// Role-Permission Matrix based on docs/00-context/roles-and-permissions.md
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_HUBS,
    PERMISSIONS.CREATE_ORDERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.CREATE_PARCELS,
    PERMISSIONS.MANAGE_PARCELS,
    PERMISSIONS.UPDATE_PARCEL_STATUS,
    PERMISSIONS.SCAN_INBOUND,
    PERMISSIONS.SCAN_OUTBOUND,
    PERMISSIONS.CREATE_ROUTE_PLANS,
    PERMISSIONS.MANAGE_ROUTES,
    PERMISSIONS.ASSIGN_DELIVERY,
    PERMISSIONS.MANAGE_DELIVERY_ZONES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_OPERATIONAL_DASHBOARD,
  ],
  [USER_ROLES.HUB_MANAGER]: [
    PERMISSIONS.MANAGE_HUBS,
    PERMISSIONS.CREATE_ORDERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.CREATE_PARCELS,
    PERMISSIONS.MANAGE_PARCELS,
    PERMISSIONS.SCAN_INBOUND,
    PERMISSIONS.SCAN_OUTBOUND,
    PERMISSIONS.UPDATE_PARCEL_STATUS,
    PERMISSIONS.VIEW_OPERATIONAL_DASHBOARD,
  ],
  [USER_ROLES.HUB_STAFF]: [
    PERMISSIONS.CREATE_ORDERS,
    PERMISSIONS.CREATE_PARCELS,
    PERMISSIONS.SCAN_INBOUND,
    PERMISSIONS.SCAN_OUTBOUND,
    PERMISSIONS.UPDATE_PARCEL_STATUS,
  ],
  [USER_ROLES.DISPATCHER]: [
    PERMISSIONS.CREATE_ROUTE_PLANS,
    PERMISSIONS.MANAGE_ROUTES,
    PERMISSIONS.ASSIGN_DELIVERY,
    PERMISSIONS.VIEW_OPERATIONAL_DASHBOARD,
  ],
  [USER_ROLES.SHIPPER]: [
    PERMISSIONS.VIEW_ASSIGNED_DELIVERIES,
    PERMISSIONS.UPDATE_DELIVERY_STATUS,
  ],
};

/**
 * Checks if a given role has a specific permission.
 */
export function hasPermission(role: UserRole | undefined, permission: Permission): boolean {
  if (!role) return false;
  const permissions = ROLE_PERMISSIONS[role];
  return permissions?.includes(permission) ?? false;
}
